# Font configuration (changes require restart)
font:
  # The normal (roman) font face to use.
  normal:
    family: FantasqueSansMono Nerd Font
    style: Regular

  # The bold font face
  bold:
    family: FantasqueSansMono Nerd Font
    # style: Bold

  # The italic font face
  italic:
    family: FantasqueSansMono Nerd Font
    # style: Italic


# Colors (Gruvbox dark)
colors:
  # Default colors
  primary:
    background: '#333233'
    foreground: '#cccccc'

  cursor:
    text:   '0xf1c1c1'
    cursor: '0x4Ca585'

  # Normal colors
  normal:
    black:   '#171717'
    red:     '#9B1300'
    green:   '#5FD2BE'
    yellow:  '#D9C679'
    blue:    '#58659A'
    magenta: '#D88E78'
    cyan:    '#719899'
    white:   '#C8C8C8'

  # Bright colors
  bright:
    black:   '#555555'
    red:     '#CF7357'
    green:   '#4CA585'
    yellow:  '#9D936B'
    blue:    '#588E9A'
    magenta: '#E09B99'
    cyan:    '#98BCBD'
    white:   '#E1E1E1'

# Window
window:
  dimensions:
    columns: 0
    lines: 0

  padding:
    x: 10
    y: 10

  dynamic_padding: true
  decorations: full
  startup_mode: Fullscreen


# Vi mode cursor colors
#vi_mode_cursor:
#  text: '#000000'
#  cursor: '#ffffff'
#
#
selection:
  save_to_clipboard: true
cursor:
  style: Block
vi_mode_cursor:
  text: CellBackground
  cursor: CellForeground

live_config_reload: true

key_bindings:
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: C, mods: Control|Shift, action: Copy }
  - { key: N, mods: Control|Shift, action: SpawnNewInstance }
