require "ofrades.plugins_settings"
require "ofrades.nvim_settings"
require "ofrades.packages"
require "ofrades.formatter"
require "ofrades.tsitter"
require "ofrades.telescope"
require "ofrades.theme"
require "ofrades.statusline"
