require "ofrades.packages"
require "ofrades.tree"
require "ofrades.plugins_settings"
require "ofrades.nvim_settings"
require "ofrades.tsitter"
require "ofrades.telescope"
require "ofrades.keymaps"
-- require "ofrades.teppz"
require "ofrades.git"
require "ofrades.statusline"
