#!/bin/bash

xrandr --output HDMI-3 --primary --mode 1920x1080 --rate 60.00
xrandr --output VGA1 --mode 1920x1080 --rate 60.00 --left-of HDMI-3

#start pcloud
pcloudcc -u mig.silva@gmail.com -d

## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"
$HOME/.config/bspwm/polybar/config
## Get colors from .Xresources -------------------------------#
xrdb ~/.Xresources
getcolors () {
	FOREGROUND=$(xrdb -query | grep 'foreground:'| awk '{print $NF}')
	BACKGROUND=$(xrdb -query | grep 'background:'| awk '{print $NF}')
	BLACK=$(xrdb -query | grep 'color0:'| awk '{print $NF}')
	RED=$(xrdb -query | grep 'color1:'| awk '{print $NF}')
	GREEN=$(xrdb -query | grep 'color2:'| awk '{print $NF}')
	YELLOW=$(xrdb -query | grep 'color3:'| awk '{print $NF}')
	BLUE=$(xrdb -query | grep 'color4:'| awk '{print $NF}')
	MAGENTA=$(xrdb -query | grep 'color5:'| awk '{print $NF}')
	CYAN=$(xrdb -query | grep 'color6:'| awk '{print $NF}')
	WHITE=$(xrdb -query | grep 'color7:'| awk '{print $NF}')
}
getcolors

bspc monitor VGA1 -d    龎
bspc monitor HDMI-3 -d    

# polybar main &

bspc config border_width 3
bspc config window_gap 13
bspc config split_ratio 0.50

bspc config focused_border_color "$GREEN" 
bspc config normal_border_color "$BACKGROUND"
bspc config active_border_color "$MAGENTA"
bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true

## Window rules -------------------------------#

# remove all rules first
bspc rule -r *:*

bspc rule -a kitty desktop='^1' follow=on focus=on
bspc rule -a Code desktop='^2' follow=on focus=on
bspc rule -a Pcmanfm desktop='^3' follow=on focus=on
bspc rule -a 'nnn' desktop='^3' follow=on focus=on
bspc rule -a calibre desktop='^4' follow=on focus=on
bspc rule -a 'calibre-ebook-viewer' desktop='^4' follow=on focus=on
bspc rule -a firefox desktop='^5' follow=on focus=on
bspc rule -a 'Google Chrome' desktop='^5' follow=on focus=on
bspc rule -a Slack desktop='^6' follow=on focus=on
bspc rule -a Evolution desktop='^6' follow=on focus=on
bspc rule -a Mattermost desktop='^6' follow=on focus=on
bspc rule -a 'Microsoft Teams - Preview' desktop='^6' follow=on focus=on
bspc rule -a WhatsApp desktop='^6' follow=on focus=on
bspc rule -a whatsapp-nativefier desktop='^6' follow=on focus=on
bspc rule -a Skype desktop='^6' follow=on focus=on
bspc rule -a 'Google Play Music Desktop Player' desktop='^7' follow=on focus=on
bspc rule -a Vlc desktop='^8' follow=on focus=on

bspc rule -a Peek center=true state=floating focus=on follow=on rectangle=1920x1080+0+0

# Special rules
bspc rule -a kitty-float state=floating follow=on focus=on center=true rectangle=700x400+0+0

## Autostart -------------------------------#

# Kill if already running
killall -9 sxhkd xsettingsd dunst xfce4-power-manager

# Lauch notification daemon
dunst \
-geom "280x50-10+40" -frame_width "1" -font "CaskaydiaCove Nerd Font" \
-lb "$BACKGROUND" -lf "$FOREGROUND" -lfr "$BLUE" \
-nb "$BACKGROUND" -nf "$FOREGROUND" -nfr "$BLUE" \
-cb "$BACKGROUND" -cf "$RED" -cfr "$RED" &

# Lauch keybindings daemon
sxhkd &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Enable power management
xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
# bash $HOME/ofrades/Downloads/iu.jpeg
feh --bg-fill ~/Downloads/iu.jpeg

# Start bspwm scripts
bspcolors
bspcomp
bspbar
bspfloat &

# Issue Tracker (Don't Remove IT)
issue_tracker.sh
