#!/usr/bin/env bash

awk '/^[a-z]/ && last {print "<small>",$0,"\t",last,"</small>"} {last=""} /^#/{last=$0}' ~/.config/sxhkd/sxhkdrc{,.common} |
    column -t -s $'\t' |
    rofi -dmenu -i -markup-rows -no-show-icons -width 1000 -lines 15 -yoffset 40

# bat ~/.config/sxhkd/sxhkdrc
#     | awk '/^[a-z]/ && last {print $0,"\t",last} {last=""} /^#/{last=$0}'
#     | column -t -s $'\t'
#     | fzf
