#!/usr/bin/env bash

awk '/^[a-z]/ && last {print "<small>",$0,"\t",last,"</small>"} {last=""} /^#/{last=$0}' ~/.config/sxhkd/sxhkdrc{,.common} |
    column -t -s $'\t' |
    rofi -dmenu -i -theme ~/.config/bspwm/scripts/rofi/styles.rasi

# bat ~/.config/sxhkd/sxhkdrc
#     | awk '/^[a-z]/ && last {print $0,"\t",last} {last=""} /^#/{last=$0}'
#     | column -t -s $'\t'
#     | fzf
