require "plugins.devicons"
require "plugins.startify"
-- require "plugins.rooter"
require "plugins.nord"
require "plugins.floaterm"
-- require "plugins.neuron"
require "plugins.fzf"
require "plugins.sign"
require "plugins.statusline"
require "plugins.sneak"
-- require "plugins.formatter"
require "plugins.tsitter"
require "plugins.tree"
require "plugins.rainbow"
